[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "django_expr"
version = "0.1.0"
requires-python = ">=3.8, <4.0"
description = "Django template tag and filter for evaluating Python expressions"
keywords = [
    "django",
    "python",
    "expression",
    "django tag",
    "django filter",
]
readme = "README.md"
authors = [
    {name = "Juro Oravec", email = "juraj.oravec.josefson@gmail.com"},
]
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    'Django>=4.2',
]
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/JuroOravec/alpinui/blob/main/packages/django-expr"


[tool.setuptools.packages.find]
where = ["src"]
include = ["django_expr*"]
exclude = ["django_expr.tests*"]
namespaces = false

[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | activate
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = "True"
known_first_party = "django_expr"

[tool.flake8]
ignore = ['E302', 'W503']
max-line-length = 119
exclude = [
  'migrations',
  '__pycache__',
  'manage.py',
  'settings.py',
  'env',
  '.env',
  '.venv',
  '.tox',
  'build',
]

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
exclude = [
    'test_structures',
    'build',
]

[[tool.mypy.overrides]]
module = "django_expr.*"
disallow_untyped_defs = true


[tool.pytest.ini_options]
testpaths = [
    "tests"
]
